### ISSUE TITLE
Bileto a ticket manager with Agile Scrum to manage project and tickets

### ISSUE THREAD

**Issue by zak39** [Probesys/bileto#679]
Hi 👋 

I used Jira for a project and I like use the story points to define the velocity to finish an issue or task. Define a sprint to plan the tasks to be carried out.
Then, obtain a burndown and burnup charts to manage the project.

I don't see this feature in another project. I think it's a good idea to implement this features.

What do you think?

**Comment by marien-probesys** [comment]
Hi @zak39, thanks for your interest for Bileto! Actually, we're building an assistance tool to manage support. I don't like to say "never", but managing projects with story points, velocity and charts is definitely not our goal at this point.

However, we have few ideas that could support your needs:

- Service Level Agreement (SLA) and statistics will help to measure and analyze time spent on the tickets
- we want to create a plugin system and an API, allowing to extend Bileto in many ways
- there is a ticket, suggesting to have a kanban view to manage the tickets (but I'm very not sure that we'll develop that)

Still, I don't think this will be enough to have a good "project manager" as we focus on an assistance tool.

**Comment by zak39** [comment]
Hi @marien-probesys , thanks for your answers :+1: 
I understand your goals.

Maybe this could help me. I will keep an eye on the project.

What is the difference between your project and the [Open Project](https://www.openproject.org/fr/)?

**Comment by marien-probesys** [comment]
> What is the difference between your project and the [Open Project](https://www.openproject.org/fr/)?

Well, I never used Open Project, but it is a project manager. Bileto is used to track incidents and requests from customers/users. Said otherwise, Bileto manages customer service, not projects. It's closer to [GLPI](https://glpi-project.org) or [Zendesk](https://www.zendesk.fr/) (closed source) than Open Project.

More specifically, users are able to open tickets (incident or request), and agents (and team of agents) answer them. Users and tickets are isolated in organizations. Also, Bileto can track time spent and account for it in contracts.

While you can certainly manage projects as well in Bileto, some features might feel out of context (e.g. tickets lifecycle), and some other will certainly be missing (e.g. estimation, milestone).

**Comment by marien-probesys** [comment]
I'm closing this issue as the requested features are not fitting the purpose of Bileto (for now at least ;)).
